name: Demo failing results (junit)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests (junit)
        run: node dist/bin/run-tests.js dist/test/examples --reporter=junit --output=test-results.xml --ci=github
      - name: Upload JUnit XML artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: junit-xml-results
          path: test-results.xml
          if-no-files-found: error

      # Run regardless of previous step results, but skip on forked PRs (no permissions to publish checks)
      - name: Publish JUnit test results
        if: ${{ !cancelled() }}
        uses: dorny/test-reporter@v1
        with:
          name: Cascade Test Results (JUnit)
          path: test-results.xml
          reporter: java-junit
          fail-on-error: false


