name: Test (tap)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests (tap)
        run: node dist/bin/run-tests.js dist/test --reporter=tap --output=test-results.tap --ci=github

      - name: Upload TAP artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tap-results
          path: test-results.tap
          if-no-files-found: error


